export const APPROX_TOKEN_PER_CHAR = 1 / 3.8;
export const MAX_SUMMARY_CHARS = 1200;
export const SUMMARY_TRIGGER_MESSAGE_COUNT = 12;
export const RECENT_MESSAGES_TO_KEEP = 8;
export const CONTEXT_WINDOW_TOKENS = 32000;
export const INPUT_BUDGET_RATIO = 0.6;
export const RESERVED_OUTPUT_TOKENS = 1200;
